ALTER TABLE users ADD firstName VARCHAR(256) NULL;
ALTER TABLE users ADD lastName VARCHAR(256) NULL;
ALTER TABLE users ADD language VARCHAR(256) NULL;
ALTER TABLE users ALTER COLUMN username SET NOT NULL;